name: Deploy Detections

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup RunReveal CLI
      run: |
        curl -L https://github.com/runreveal/homebrew-runreveal/releases/latest/download/runreveal-linux-amd64.tar.gz > runreveal-linux-amd64.tar.gz
        tar -xvf runreveal-linux-amd64.tar.gz
        chmod +x runreveal
        rm runreveal-linux-amd64.tar.gz
        
    - name: Deploy Detections
      env:
        RUNREVEAL_TOKEN: ${{ secrets.RUNREVEAL_API_KEY }}
      run: |
        ./runreveal detections sync -d detections